version: '3.8'

services:
  db:
    image: postgres:15
    container_name: task_db
    restart: always
    environment:
      POSTGRES_USER: krasnovkd21
      POSTGRES_PASSWORD: yes
      POSTGRES_DB: petProjectDB
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

